config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do
  get 'candidate/show_details'

  get 'election/index'

  get 'election/show_candidate_list'

  
  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda {|u| u.is_admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end
  
  #map.elections '/elections', :controller => 'elections', :action => 'show_candidate_list'
  get '/election/:id', to: 'election#show_candidate_list', as: 'elections'
  get '/candidate/:id', to: 'candidate#show', as: 'candidate'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin

  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'
  get '/terms' => 'pages#terms', as: 'terms'
  get '/privacy' => 'pages#privacy', as: 'privacy'

  # OAuth
  oauth_prefix = Rails.application.config.auth.omniauth.path_prefix
  get "#{oauth_prefix}/:provider/callback" => 'users/oauth#create'
  get "#{oauth_prefix}/failure" => 'users/oauth#failure'
  get "#{oauth_prefix}/:provider" => 'users/oauth#passthru', as: 'provider_auth'
  get oauth_prefix => redirect("#{oauth_prefix}/login")

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end
  get '/home' => 'users#show', as: 'user_home'

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  get 'robots.:format' => 'robots#index'

  root 'pages#home'
end

app/models/election.rb
class Election < ActiveRecord::Base
	has_many :candidates
	has_many :election_outcomes
  
end

app/controllers/election_controller.rb
class ElectionController < ApplicationController
  skip_authorization_check
  
  def index
    @elections = Election.all
    
  end

  def show_candidate_list
    @election = Election.find(params[:id])
    @candidates = Candidate.where(:election_id => 1)
    @output = {}
    
    if (params.has_key?(:search))
      categories = params[:search].split(';')
      
      total_params = categories.size
      @candidates.each do |x|
        @output[x.id] = (100*(x.standpoints.where(name: categories)).size / total_params)
      end
      @output = Hash[@output.sort_by{|k,v| -v}] 
    end
    
  end
end

app/helpers/election_helper.rb
module ElectionHelper
end

app/views/election/index.html.haml
/ Le styles
/%link{:href => "http://talkslab.github.io/metro-bootstrap/dist/css/metro-bootstrap.min.css", :rel => "stylesheet", :type => "text/css"}/
%link{:href => "http://talkslab.github.io/metro-bootstrap/styles/font-awesome.min.css", :rel => "stylesheet"}/
/ documentation styles
%link{:href => "http://talkslab.github.io/metro-bootstrap/styles/docs.css", :rel => "stylesheet", :type => "text/css"}/
/ Le HTML5 shim, for IE6-8 support of HTML5 elements
/[if lt IE 9]
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
/ link rel="stylesheet/less" href="less/bootstrap.less" type="text/css" /
/ link rel="stylesheet/less" href="less/responsive.less" type="text/css" /
/ script src="js/less-1.3.3.min.js"></script
/ append ‘#!watch’ to the browser URL, then refresh the page.
%link{:href => "css/bootstrap.min.css", :rel => "stylesheet"}/
%link{:href => "css/style.css", :rel => "stylesheet"}/
/ HTML5 shim, for IE6-8 support of HTML5 elements
/[if lt IE 9]
<script src="http://talkslab.github.io/metro-bootstrap/js/html5shiv.js"></script>
/ Fav and touch icons
%script{:src => "js/jquery.min.js", :type => "text/javascript"}
%script{:src => "js/bootstrap.min.js", :type => "text/javascript"}
%script{:src => "js/scripts.js", :type => "text/javascript"}
.container
  .row.clearfix
    .col-md-10.column
      .page-header
        %h1#tiles Election List
      .btn-group
        %button.btn.btn-default Country
        %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown"}
          %span.caret
        %ul.dropdown-menu
          %li
            %a{:href => "#"} Action
          %li.disabled
            %a{:href => "#"} Another action
          %li.divider
          %li
            %a{:href => "#"} Something else here
      .btn-group
        %button.btn.btn-default District
        %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown"}
          %span.caret
        %ul.dropdown-menu
          %li
            %a{:href => "#"} Action
          %li.disabled
            %a{:href => "#"} Another action
          %li.divider
          %li
            %a{:href => "#"} Something else here
      .btn-group
        %button.btn.btn-default Date
        %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown"}
          %span.caret
        %ul.dropdown-menu
          %li
            %a{:href => "#"} Action
          %li.disabled
            %a{:href => "#"} Another action
          %li.divider
          %li
            %a{:href => "#"} Something else here
      .bs-docs-section
        .bs-example
          .row
            .row.clearfix
              / Wide Tile
              .col-md-4.column
                .col-sm-6.col-md-6
                  .thumbnail.tile.tile-wide.tile-green
                    %a{:href => "#"}
                      %br/
                      %h2.half-line Election Name
                      %h4.half-line Country - District
                      %h4.half-line Election Date
                      %h6 This is the overview of the election that tells you what the elections is about in one or two sentences
              / Wide Tile
              .col-md-4.column
                .col-sm-6.col-md-6
                  .thumbnail.tile.tile-wide.tile-red
                    %a{:href => "#"}
                      %br/
                      %h2.half-line Election Name
                      %h4.half-line Country - District
                      %h4.half-line Election Date
                      %h6 This is the overview of the election that tells you what the elections is about in one or two sentences
              / Wide Tile
              .col-md-4.column
                .col-sm-6.col-md-6
                  .thumbnail.tile.tile-wide.tile-blue
                    %a{:href => "#"}
                      %br/
                      %h2.half-line Election Name
                      %h4.half-line Country - District
                      %h4.half-line Election Date
                      %h6 This is the overview of the election that tells you what the elections is about in one or two sentences
              / Wide Tile
              .col-md-4.column
                .col-sm-6.col-md-6
                  .thumbnail.tile.tile-wide.tile-orange
                    %a{:href => "#"}
                      %br/
                      %h2.half-line Election Name
                      %h4.half-line Country - District
                      %h4.half-line Election Date
                      %h6 This is the overview of the election that tells you what the elections is about in one or two sentences


/- @elections.each do |i|
/    %p
/= button_to(i.name, '/election/'+i.id.to_s,:method => :get)
/= time_ago_in_words(i.vote_date)
    
    
    

app/views/election/show_candidate_list.html.haml
- aa = []

- @candidates.each do |i|
  - i.standpoints.each do |j|
    - aa << j.name
- aa = aa.uniq

.row.clearfix.text-center{:style => "margin-bottom: 15px;"}
  %p.lead Select the issues that you're interested in 
.row.clearfix
  .col-md-2.column
  .col-md-8.column.text-justify
    %div.btn-group
    - aa.uniq.each do |q|
      %button.btn.large.btn-default{:style => "margin-bottom: 15px; margin-right: 10px", :class => q.gsub(" ", ""), :onclick => '$(search).val($(search).val() + "' + q + '" + \';\'); $(".' + q.gsub(" ", "") + '").addClass("btn-success")'}= q
    .col-md-2.column
   
.row.clearfix

= form_tag elections_path, :method => 'get' do
  = text_field_tag :search, params[:search], :value=> '', :hidden => true
  = submit_tag "Update", :name => nil 

- if(@output.size > 0)
  %table.table
    %thead
      %th
        Name
      %th
        Overview
      %th
        \% match
    %tbody
      - @output.each do |i|
        %tr
          %td= link_to(@candidates.find(i[0]).name,@candidates.find(i[0]))
          %td= @candidates.find(i[0]).overview
          %td= i[1].to_s + '%'